export const screenConstants = {
   LOGIN: 'LOGIN',
   PROFILE: 'PROFILE',
   MAIN: 'MAIN',
   LOGOUT: 'LOGOUT',
   CONTACTS: 'CONTACTS',
   GROUPS: 'GROUPS',
   CHATS: 'CHATS',
   ROOM: 'ROOM',
   TABS: 'TABS',
   MESSAGE: 'MESSAGE',
   CALL: 'CALL',
   COMPACT:'COMPACT',
   CURRENT_SCREEN:'CURRENT_SCREEN',

   INCOMMING_CALL:'INCOMMING_CALL',
   ACCEPT_INCOMMING_CALL:'ACCEPT_INCOMMING_CALL',
   DECLINE_INCOMMING_CALL:'DECLINE_INCOMMING_CALL',

   OUTGOING_CALL:'OUTGOING_CALL',
   CANCEL_OUTGOING_CALL:'CANCEL_OUTGOING_CALL',
  //  DECLINE_INCOMMING_CALL:'DECLINE_INCOMMING_CALL',

   
 };
 
