export const userConstants = {
   LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
   LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
   LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
   LOGOUT: 'USER_LOGOUT',
   USER: 'USER',
   PROFILE:'PROFILE',
   CHANNELS:'CHANNELS',
   CURRENT_CHAT:'CURRENT_CHAT',
   CURRENT_MESSAGES:'CURRENT_MESSAGES',
   PUBSUB:'PUBSUB',
   SUBSCRIBERS:'SUBSCRIBERS',
   CURRENT_CHANNEL:'CURRENT_CHANNEL',
   ACTIVE_CHANNEL:'ACTIVE_CHANNEL',
   CUSTOM_NAVIGATION:'CUSTOM_NAVIGATION',
   FRIENDLIST:"FRIENDLIST",
   CLEAR_USER_DATA:'CLEAR_USER_DATA'
 
 };
 
